#!/bin/bash

cd "$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )" || exit

SUPPRESS_WARNINGS=-Wignore
PGPT_PROFILES=local,cuda,logger poetry run python $SUPPRESS_WARNINGS -m private_gpt
