# https://stackoverflow.com/questions/68740136/uvicorn-log-the-errror-message-instead-of-infouvicorn-errorapplicationi
version: 1
disable_existing_loggers: True
formatters:
  default:
    format: '%(asctime)s - uvicorn - %(levelname)s - %(message)s'
  access:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  default:
    formatter: default
    class: logging.StreamHandler
    stream: ext://sys.stderr
  access:
    formatter: access
    class: logging.StreamHandler
    stream: ext://sys.stdout
loggers:
  uvicorn.error:
    level: WARN
    handlers:
      - default
    propagate: no
  uvicorn.access:
    level: WARN
    handlers:
      - access
    propagate: no
root:
  level: WARN
  handlers:
    - default
  propagate: no
